version: '3.8'

services:
  village-bill:
    build:
      context: .
      dockerfile: Dockerfile
    image: village-bill:latest
    container_name: village-bill
    restart: always # 如果服务意外挂掉，自动重启
    ports:
      - "8618:8080" # 映射主机的 8618 端口到容器内的 8080
    volumes:
      # 持久化主要数据库文件将由挂载整个 data 目录实现，而不是单个文件
      # 避免在宿主机上无法自动创建相关缓存文件 (-wal, -shm) 导致数据库无法打开
      - ./data:/app/data
      # 持久化上传的文件目录
      - ./uploads:/app/uploads
      # 映射日志文件以便于在宿主机上查看
      - ./logs.txt:/app/logs.txt
      - ./logs.err:/app/logs.err
    # 设置时区和数据库路径参数
    environment:
      - TZ=Asia/Shanghai
      - DB_PATH=data/village-bill.db
